import { applyDecorators } from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiHeader } from '@nestjs/swagger';
import { CreateUserDto } from '../dto/create-user.dto';

export const ApiCreateUser = () => {
  return applyDecorators(
    ApiOperation({ summary: 'Create a new user' }),
    ApiResponse({
      status: 201,
      description: 'The user has been successfully created.',
      type: CreateUserDto,
    }),
    ApiResponse({ status: 400, description: 'Bad request.' }),
  );
};

export const ApiGetAllUsers = () => {
  return applyDecorators(
    ApiHeader({
      name: 'x-auth',
      description: 'Token generated by Login',
      required: true,
      schema: { type: 'string', example: 'your-jwt-token' },
    }),
    ApiOperation({ summary: 'Get all users' }),
    ApiResponse({
      status: 200,
      description: 'Return all users for admin',
      type: [CreateUserDto],
    }),
  );
};
